language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest

install:
  - pip install --upgrade pip setuptools wheel
  - sudo apt-get install python-numpy python-scipy gfortran
  - pip install numpy
  - pip install scipy

# command to run tests
script:
  - python setup.py pytest

#after_success:
#  - bash <(curl -s https://codecov.io/bash)
